import Port
import time
def Hello():
    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")
    print("/")
    time.sleep(4)


    time.sleep(1)
    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")
    print("/")
    time.sleep(4)


    time.sleep(1)
    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")

    time.sleep(1)
    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    time.sleep(1)
    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")
    print("/")
    time.sleep(4)


    time.sleep(1)
    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("1")
    time.sleep(1)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")

    time.sleep(1)
    Port.sendCommand("4")
    time.sleep(2)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    time.sleep(1)
    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")
    print("/")
    time.sleep(4)

    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")

    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")

    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")
    print("/")

def S_O_S():
    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")
    print("/")

    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")

    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")

    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")
    print("/")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")
    print("/")

def OVER():
    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")

    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")

    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")
    print("/")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")
    print("/")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")
    print("/")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")

    Port.sendCommand("1")
    time.sleep(2)
    Port.sendCommand("0")
    time.sleep(1)
    print("-")

    Port.sendCommand("4")
    time.sleep(1)
    Port.sendCommand("5")
    time.sleep(1)
    print(".")
    print("/")

